// server/routes/publicQuotations.ts
import { Router } from "express";
import { supaAdmin } from "../supabaseAdmin.js";

const r = Router();

function isUuid(v: string) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(v || "").trim());
}
function nowIso() {
  return new Date().toISOString();
}

/**
 * GET /api/public/quotation-link?quotation_id=123
 * - Creates a public link token in quotation_public_links (or returns existing active one)
 * - You can call this from your UI when user clicks "Share quotation"
 */
r.get("/quotation-link", async (req, res) => {
  try {
    const supabase = supaAdmin();

    const rawId = String(req.query.quotation_id || "").trim();
    const quotationId = Number(rawId);

    if (!Number.isFinite(quotationId) || quotationId <= 0) {
      return res.status(400).json({ ok: false, error: "Invalid quotation_id" });
    }

    // 1) Check quotation exists
    const { data: q, error: qErr } = await supabase
      .from("quotations")
      .select("id")
      .eq("id", quotationId)
      .maybeSingle();

    if (qErr) throw qErr;
    if (!q) return res.status(404).json({ ok: false, error: "Quotation not found" });

    // 2) Reuse an existing active link if any
    const { data: existing, error: eErr } = await supabase
      .from("quotation_public_links")
      .select("id, token, quotation_id, expires_at, revoked_at, created_at")
      .eq("quotation_id", quotationId)
      .is("revoked_at", null)
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    if (eErr) throw eErr;

    if (existing?.token && isUuid(existing.token)) {
      // If expired, ignore and create new
      if (!existing.expires_at || new Date(existing.expires_at).getTime() > Date.now()) {
        return res.json({ ok: true, server_time: nowIso(), link: existing });
      }
    }

    // 3) Create a new link (no expiry by default; set expires_at if you want)
    // NOTE: token is usually generated by DB default (uuid). If you don't have that,
    // you must generate UUID in code and insert it.
    const { data: created, error: cErr } = await supabase
      .from("quotation_public_links")
      .insert({ quotation_id: quotationId })
      .select("id, token, quotation_id, expires_at, revoked_at, created_at")
      .single();

    if (cErr) throw cErr;

    return res.json({ ok: true, server_time: nowIso(), link: created });
  } catch (e: any) {
    console.error("publicQuotations error:", e?.message || e);
    return res.status(500).json({ ok: false, error: e?.message || "Server error" });
  }
});

export default r;
